# Generated by Django 5.0.1 on 2024-01-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='thumnail',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
