# Generated by Django 5.0.1 on 2024-01-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_postmodel_thumnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='thumnail',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
