# Generated by Django 5.0.1 on 2024-01-20 05:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_postmodel_thumnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name=' عنوان دسته بندی')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش داده شود')),
                ('slug', models.SlugField(unique=True, verbose_name='کلمه کلیدی')),
                ('position', models.IntegerField(verbose_name='موقعیت')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['position'],
            },
        ),
        migrations.AlterModelOptions(
            name='postmodel',
            options={'verbose_name': 'پست', 'verbose_name_plural': ' پست ها'},
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='description',
            field=models.TextField(verbose_name='شرح عنوان'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='is_enable',
            field=models.BooleanField(default=False, verbose_name='فعالیت'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان تولید'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='کلمه کلیدی'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='thumnail',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(help_text='Insert Name Post', max_length=50, verbose_name='عنوان'),
        ),
    ]
