# Generated by Django 5.0.1 on 2024-01-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_categorymodel_alter_postmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='category',
            field=models.ManyToManyField(to='posts.categorymodel', verbose_name=' دسته بندی'),
        ),
    ]
