# Generated by Django 5.0.1 on 2024-01-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.ManyToManyField(related_name='postmodel', to='posts.categorymodel', verbose_name=' دسته بندی'),
        ),
    ]
