# Generated by Django 5.0.1 on 2024-01-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_postmodel_thumnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='thumnail',
            field=models.ImageField(upload_to='images/', verbose_name='تصویر'),
        ),
    ]
