# Generated by Django 5.0.1 on 2024-01-29 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_postmodel_thumnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
