# Generated by Django 5.0.1 on 2024-02-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_rename_thumnail_postmodel_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='color',
            field=models.CharField(choices=[('b', 'black'), ('w', 'withe')], default='b', max_length=10, verbose_name='رنگ'),
        ),
    ]
