# Generated by Django 5.0.1 on 2024-02-01 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_postmodel_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='color',
        ),
    ]
