# Generated by Django 5.0.1 on 2024-02-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_postmodel_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
